server:
  port: 8002

spring:
  application:
    name: strumcode-short-link-admin
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:prod}.yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
#  data:
#    redis:
#      host: common-redis-dev.magestack.cn
#      port: 19389
#      password: Sm9sVXBOYJjI030b5tz0trjpzvZzRhtZmEbv0uOImcD1wEDOPfeaqNU4PxHob/Wp

  cloud:
    nacos:
      discovery:
        server-addr: common-nacos-dev.magestack.cn:8848

short-link:
  group:
    max-num: 20
  flow-limit:
    enable: true
    time-window: 1
    max-access-count: 4000
